type: chart
deployments:
  - chart: logging-central
    release: logging-central
    test: 
      values:
        - key: elasticsearch-chart.data_create_storage_class
          value: true
        - key: elasticsearch-chart.master_create_storage_class
          value: true
        - key: elasticsearch-chart.data_storage_class_value
          value: esdatasc
        - key: elasticsearch-chart.master_storage_class_value
          value: esmastersc
        - key: kibana-chart.replicas
          value: 1
        - key: kibana-chart.cpu_limit 
          value: 50m
        - key: kibana-chart.cpu_requests 
          value: 50m
        - key: kibana-chart.mem_limit 
          value: 50Mi
        - key: kibana-chart.mem_requests 
          value: 50Mi
helmRepos:
   - name: cnct-migrations
     url: http://charts.migrations.cnct.io
prod: 
  doDeploy: none
