type: chart
deployments:
  - chart: logging-central
    release: logging-central
    test: 
      values:
        - key: elasticsearch-chart.data_create_storage_class
          value: true
        - key: elasticsearch-chart.master_create_storage_class
          value: true
        - key: elasticsearch-chart.data_storage_class_value
          value: esdatasc
        - key: elasticsearch-chart.master_storage_class_value
          value: esmastersc
helmRepos:
   - name: cnct-migrations
     url: http://charts.migrations.cnct.io
prod: 
  doDeploy: none
