# Default values.

name: central_logging

central:
  ci_testing: false
  test:
    image: quay.io/samsung_cnct/e2etester:prod
    account: elastic
    password: changeme

elasticsearch-chart:
  name: elasticsearch
  port: 9200

  data_memory_limits: 3Gi
  data_memory_requests: 3Gi
  data_Xms_Xmx: 1g

kibana:
  name: kibana
  port: 5601

kibana:
  cpu_limit: 100m
  cpu_requests: 100m
  mem_limit: 512Mi
  mem_requests: 512Mi

curator:
  name: curator
  schedule: "30 3 * * *"
  action: delete_indices
  description:
    Delete indices older than 14 days and prefixed with logstash-.
    Ignore the error if the filter does not result in an actionable
    list of indices (ignore_empty_list) and exit cleanly.
  
  filters:
  - filtertype: pattern
    kind: prefix
    value: "logstash-"
    exclude: False
  - filtertype: age
    source: name
    timestring: '%Y.%m.%d'
    direction: older
    unit: days
    unit_count: 14
    field: null
    stats_result: null
    epoch: null
    exclude: False
  
  logging:
    loglevel: INFO
