# Default values.

name: central_logging

central:
  ci_testing: false
  test:
    image: quay.io/samsung_cnct/e2etester:prod
    account: elastic
    password: changeme

elasticsearch-chart:
  name: elasticsearch
  port: 9200

  data_memory_limits: 16Gi
  data_memory_requests: 16Gi
  data_Xms_Xmx: 8g
  # master_memory_limits: 2Gi
  # master_memory_requests: 2Gi
  # master_Xms_Xmx: 1g

  security:
    password: "changeme"
  services:
    es:
      public: true
      # this can be set on the commmand line as; 
      # elasticsearch-chart.services.es.annotations[0].key="external-dns.alpha.kubernetes.io/hostname",elasticsearch-chart.services.es.annotations[0].value=esold.mikeln.cluster.cnct.io
      annotations:
      - key: "external-dns.alpha.kubernetes.io/hostname"
        value: "es.<newdomain>.cluster.cnct.io" 

  external-dns:
   # can be set on the commandline as:
   # domainFilters[0]="mikeln.cluster.cnct.io"
   # 
   #  has to match the above without es
   domainFilters: [ "<newdomain>.cluster.cnct.io" ]
   aws:
     secretKey: COMMAND_LINE
     accessKey: COMMAND_LINE

kibana:
  name: kibana
  port: 5601
  security:
    password: "changeme"
  cpu_limit: 100m
  cpu_requests: 100m
  mem_limit: 512Mi
  mem_requests: 512Mi

curator:
  name: curator
  schedule: "30 3 * * *"
  action: delete_indices
  security:
    password: "changme"
  
  logstashFilters:
    direction: older
    unit: days
    unit_count: 14
  
  logsystemdFilters:
    direction: older
    unit: days
    unit_count: 14
  
  logging:
    loglevel: INFO
